### ISSUE TITLE
[Experiment] detectron2 baseline

### ISSUE THREAD

**Issue by updaun** [boostcampaitech3/level2-object-detection-level2-cv-09#4]
### What?
- detectron2 Faster R-CNN

### Why?
- model test

### Todo
- [x] 개발환경 세팅하기
- [x] detectron2 학습 시켜보기
- [x] 학습 시간 공유하기
- [x] 결과 제출 하기
