### ISSUE TITLE
[New feature] Add val_pipeline

### ISSUE THREAD

**Issue by updaun** [boostcampaitech3/level2-object-detection-level2-cv-09#65]
### What?
- Add val_pipeline

### Why?
- to catch train mistake

### Todo
- [x] swinB_cascade val_pipeline 추가
- [x] swinL_cascade val_pipeline 추가
- [x] swinS_cascade val_pipeline 추가
- [x] swinB_cascade_kfold val_pipeline 추가
